pages:
  script:
    - mkdir -p public/css
    - mkdir -p public/js
    - cp css/styles.css public/css/styles.css
    - cp js/app.js public/js/app.js
    - cp index.html public/index.html
  artifacts:
    paths:
      - public